### ISSUE TITLE
Parsing "variable-length tuple of homogeneous type" fails

### ISSUE THREAD

**Issue by dhermes** [jonparrott/sphinx-docstring-typing#2]
For example:

```
        edges (Tuple[.Curve, ...]): The boundary edges of the
            curved polygon.
```

From: https://github.com/dhermes/bezier/blob/d810585c9ace148e076e5ce0733149409c4213db/bezier/curved_polygon.py#L67-L68

**Comment by theacodes** [comment]
Probably just need to add a case to the AST code for ellipsis.

**Comment by theacodes** [comment]
Should be fixed by 0.0.2.

**Comment by dhermes** [comment]
You so fancy!

**Comment by dhermes** [comment]
@jonparrott I just updated and it fails with

```
        edges (Tuple[.Curve, ...]): The boundary edges of the
            curved polygon.
```

but passes with

```
        edges (Tuple[Curve, ...]): The boundary edges of the
            curved polygon.
```

----

Failure:

```
Warning, treated as error:
:type edges: Tuple[.Curve, ...]: invalid syntax (<unknown>, line 1)sphinx-docstring-typing: Un-parseable line in docstring: 
        >%s 

Exception: %s
```

(`HEAD` is at https://github.com/dhermes/bezier/commit/0b66aa1675f1e5a0128e23be88ddc8d29d441522)

**Comment by theacodes** [comment]
Is it just the `.` that causes it to choke? I can add a new test case for
that and see what's up.

**Comment by dhermes** [comment]
Yup, just the ``.``. I just [went with][1] `Tuple[~bezier.curve.Curve, ...]` and moved on.

[1]: https://github.com/dhermes/bezier/blob/955621ed144f38b73ac5a7c91b58fac1702c19ca/bezier/curved_polygon.py#L120

**Comment by theacodes** [comment]
Yeah, so I don't think I'll ever be able to support `.Curve`, because `.Curve` isn't valid Python syntax.

**Comment by dhermes** [comment]
But neither is `~bezier.curve.Curve`? It's a mix of Sphinx/RST and typing?

**Comment by theacodes** [comment]
`~` is a totally valid Python unary operator. :)

**Comment by dhermes** [comment]
Right but it doesn't work on all objects:

```python
>>> import bezier
>>> ~bezier
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: bad operand type for unary ~: 'module'
>>> import bezier.curve
>>> ~bezier.curve
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: bad operand type for unary ~: 'module'
>>> ~bezier.curve.Curve
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: bad operand type for unary ~: 'type'
```

**Comment by theacodes** [comment]
It doesn't have to be runnable Python, just parseable.

**Comment by dhermes** [comment]
Right. But should the goal of a Sphinx extension not be parsing valid Sphinx?

**Comment by theacodes** [comment]
Not necessarily, this extension is specifically for parsing Python 3 type
annotations and transforming them into sphinx syntax. So it follows that
the primary syntax is Python. Though I agree some affordances need to be
made so we can support sphinx features such as `.Something` and
`~something.Something`.
