### ISSUE TITLE
`app.verbose()` is being dropped in Sphinx 2.0

### ISSUE THREAD

**Issue by dhermes** [jonparrott/sphinx-docstring-typing#7]
The line https://github.com/theacodes/sphinx-docstring-typing/blob/2aea0faecf82a825b5b203a28c81eb87063f533a/sphinx_docstring_typing/__init__.py#L152 results in "scary" warnings, e.g.

```
.../site-packages/sphinx/application.py:413: RemovedInSphinx20Warning: app.verbose() is now deprecated. Use sphinx.util.logging instead.
  RemovedInSphinx20Warning)
```

Seems like the fix is to "Use `sphinx.util.logging` instead"?

**Comment by theacodes** [comment]
Probably. I'm also still surprised this extension is needed at all.

**Comment by dhermes** [comment]
I.e. you're surprised Sphinx doesn't support it?

**Comment by theacodes** [comment]
Ya
